### ISSUE TITLE
3DS max crashes after export.

### ISSUE THREAD

**Issue by 62316e** [awaytools/AwayExtensions-3dsmax#1]
1. Open 3ds max
2. Create a box (default)
3. Export to AWD (default settings - animation, flash checked)
4. profit (crash)

**Comment by 62316e** [comment]
Crashes when exporting animation.

**Comment by persanker** [comment]
Can you upload the max file you used?

**Comment by 62316e** [comment]
Sure. Please leave your email or PM me.
Still have some crashes.

**Comment by persanker** [comment]
Sure, You can contact with me by Skype. My account is avagrant158@126.com(also my email address)

**Comment by 80prozent** [comment]
new 3dsmax exporter is on the way
issue should be solved

can be reopened if still exists with the new version
