### ISSUE TITLE
Skeleton animation problem

### ISSUE THREAD

**Issue by leucocyte** [awaytools/AwayExtensions-3dsmax#13]
When you export the model with skeleton bones attached axes of rotation changed from the original.
Additionally, in some cases, the angle of rotation (bones) increases twice about.
I'm attaching preview of the problem (tested in away builder), 3dmax source file and exported awd.

http://taern.com/files/awd-test.rar

![max vs away](https://cloud.githubusercontent.com/assets/3738984/3442295/8468417e-0112-11e4-91e5-134d5765a8ad.jpg)

**Comment by 80prozent** [comment]
Hey. I will take a look this, later when i am home.

**Comment by leucocyte** [comment]
We've found what was the cause:
Mesh pivot axes should be oriented same way as the root bone pivot axes.
Otherwise we're getting those strange deformations after export to awd.

**Comment by 80prozent** [comment]
hey again
yeah, that is a restriction for the skeleton-export.
Root-joint transform matrix must be the same as skinned-mesh transform matrix.
Best is to put them both into one container (dummy) and both have identity-matrix as transform matrix.
This way, the exporter will work, but you also can move the container/dummy, in your scene.

Hope that makes sense :)
