### ISSUE TITLE
The "Loop" property in Animation Clip Manager can not be exported

### ISSUE THREAD

**Issue by liaocheng** [awaytools/AwayExtensions-3dsmax#16]
I'm not sure if my approach is correct. But when I open the Animation Clip Manager window, no matter what the status of the "Loop" check box I set, the exported AWD animation clip ( SkeletonClipNode in Away3D ) always set looping true.

**Comment by 80prozent** [comment]
Hi
I found a fix that should fix the issue. Atm i have no setup in place to test myself.
Please check if this *.dle fixes the issue:
http://differentdesign.de/downloads/maxawdexporter_2014_64.dle

**Comment by liaocheng** [comment]
Thank you very much for the quick fix! It works well now. But another two properties "stichfinal" and " transform" seem not be exported as well. Could you please check that?
BTW, I found there is an releated issue in AWD2Parser: https://github.com/away3d/away3d-core-fp11/issues/707

**Comment by 80prozent** [comment]
Hey 
You are right about the issue in the AWD2parser. Comment on there.
This should fix both "stitchfinal" and  "loop". 
The "transform" - property has only effect on export, so no need to save it. 
For skeletonAnimation, it defines if the transformation of the root-joint should get included on export, or if the transform of the root-joint is baked into the transformations of the child-joints.
For VertexAnimation, it defines, if the transformation of the mesh should be baked into the Vertex-Animation

**Comment by 80prozent** [comment]
Should be fixed by commit 
https://github.com/awaytools/AwayExtensions-3dsmax/commit/f9845ff2dae19305e186285aa10df78b8063b57a
