### ISSUE TITLE
Export Vertex Color

### ISSUE THREAD

**Issue by liaocheng** [awaytools/AwayExtensions-3dsmax#22]
Hello Robin
I'm trying to implement vertex color exporting based on your plugins. But I am troubled by a question. This is not a question about your plugin but about 3ds max plugin.
Here's my question:
1. Select any mesh
![image](https://cloud.githubusercontent.com/assets/958492/5585318/b6c9e072-90e2-11e4-967f-b323c13d349e.png)
2. Select Vertex in Editable Mesh
![image](https://cloud.githubusercontent.com/assets/958492/5585322/d65e1d86-90e2-11e4-955d-e6f50491cdfa.png)
3. Scroll down to Surface Properties
![image](https://cloud.githubusercontent.com/assets/958492/5586021/a5195642-90fa-11e4-8aca-7e2b061f65c9.png)
4. Select any vertex on the mesh
![image](https://cloud.githubusercontent.com/assets/958492/5586033/f64b02f4-90fa-11e4-801c-60c5f0586a6b.png)
5. Set color and alpha on Surface Properties pannel
![image](https://cloud.githubusercontent.com/assets/958492/5586047/5331183c-90fb-11e4-98f8-fb3a51a82ca1.png)
Now this vertex on the mesh should have the color with alpha value.
And then in plugin (maxawdexporter_geometry.cpp), I can get the color value by 
`mesh.vertCol[vIdx]` (vIdx is the index of the vertex)
However I don't know how to get the alpha value. 
I tried 
`mesh.setVDataSupport(VDATA_ALPHA);`
`mesh.vertexFloat(VDATA_ALPHA)[vIdx];`
But it didn't work ( `mesh.vertexFloat(VDATA_ALPHA)[vIdx]` always was 1.0) . 

I'm sorry to bother you. Any suggestion is appreciated.
Regards

**Comment by 80prozent** [comment]
hey liaocheng
I am working on the plugin + libawd right now, and will upload a new version for both in next days.
To get the vertex-color and vertex-alpha, i would try to use the IGameMesh-interface instead of the Mesh-interface.
Right now i cannot test, becausei have some refactoring going on that prevents me from compile...
To get the alpha and color for a vertex, i suspect it will work something like this:

```
FaceEx * f=facelist[idx];    // get pointer to face - is already in the code.
for (v=2; v>=0; v--) {        // loop over verts of face - is already in the code
    Point3 vertexColor=igame_mesh->GetColorVertex(f->color[v]); // returns (-1,-1,-1) if no color is set for vertex
    float vertexAlpha=igame_mesh->GetAlphaVertex(f->alpha[v]); // return -1 if no alpha is set for vertex
}
```

**Comment by liaocheng** [comment]
You are right. It works for me now.
Thank you very much, Robin!
